### ISSUE TITLE
No new commits since previous tag. Skipping...

### ISSUE THREAD

**Issue by artem-tomyuk** [anothrNick/github-tag-action#96] opened 2020-11-24 08:26 UTC
Hi,
tag not being created with message: 
No new commits since previous tag. Skipping...
workflow was triggered manually with workflow_dispatch, and there was no new commits in branch but doc's says:
 - If triggered on your repo's default branch (master if unchanged), the bump version will be a release tag.
so as i understand if job was manually triggered via workflow_dispatch and there were no new commits new TAG should be created? 
action settings:
*** CONFIGURATION ***
	DEFAULT_BUMP: minor
	WITH_V: true
	RELEASE_BRANCHES: master
	CUSTOM_TAG: 
	SOURCE: .
	DRY_RUN: false
	INITIAL_VERSION: 0.0.0
	TAG_CONTEXT: repo
	PRERELEASE_SUFFIX: beta
	VERBOSE: true

**Comment by billypchan** [comment] 2021-11-25 18:13
I also encounter this issue.

**Comment by vukomir** [comment] 2022-09-03 22:23
same here

**Comment by sammcj** [comment] 2022-09-13 05:42
Hello - is this still an issue with v1.45.0?

**Comment by sbe-arg** [comment] 2022-09-27 21:09
@vukomir can you share some examples? I can't replicate this atm

**Comment by sbe-arg** [comment] 2022-09-28 01:33
Whats the principle to bump a tag if there is no code change? SHA is the identifier of the status of the entire branch is has not change then no version bump should be required from a practice point of view.

It is by design to skip tag if there is no code change.

**Comment by sbe-arg** [comment] 2022-09-28 01:38
Closing issue if we want to request a feature to bump tags regardless no having code changes we should update this issue or open a new one clarifiying specific requirements.

This can be done by introducing a different #something veriification or IGNORE_SHA_CHECKS or other.

**Closed by sbe-arg** 2022-09-28 01:38 UTC
