### ISSUE TITLE
Add Prefix to Tags

### ISSUE THREAD

**Issue by hsimjee** [anothrNick/github-tag-action#72] opened 2020-07-28 02:54 UTC
Hey,
First and foremost, great work with this library. I ran into an issue where I wanted to add a prefix to the tag besides "v". Is there any way we can make that change?
Thanks

**Comment by fidou** [comment] 2021-05-04 09:49
Hi, I have the same wish and would love to be able to have custom prefix. thanks

**Comment by NickLarsenNZ** [comment] 2021-12-16 08:15
Same here. We have two branches that have diverged and need their own set of tags.

Eg: `main` is normal semver `x.x.x`, while the `other` branch needs semver tags but separate, so a prefix would be good. We could get away with using `v`, but it's ambiguous.

Bumping the `other` branch should **not** take the normal semver tags that reference commits on `main` so that their versions move independently.

_It's an interim hack for us, eventually `other` branch will disappear. Splitting the repo just moves the toil elsewhere._

**Comment by fabricepipart** [comment] 2021-12-17 06:26
The problem is that a prefix does not follow strict semantic versioning (as per https://semver.org/ at least). That is why the RELEASE_BRANCHES parameter was introduced. To have your `main` branch as `x.x.x` and other branches postfixed with a commit ID.
That may not be very explicit to know what branch the tag comes from. Maybe we could have a more explicit postfix like the branch name?

**Comment by NickLarsenNZ** [comment] 2021-12-17 12:06
I don't think that should matter. The valid semantic version is after the prefix, so the prefix can be stripped for calculating the bump version, then added back on when tagging.

The `v` prefix is also not valid SemVer, but can appear in tags.

**Comment by sammcj** [comment] 2022-09-13 05:47
Hello - is this still an issue with v1.45.0 and required?

**Comment by sbe-arg** [comment] 2022-09-27 21:12
Closing please reopen if necesary

**Closed by sbe-arg** 2022-09-27 21:12 UTC
